[server]
host = "0.0.0.0"
port = 8080

[rpc]
# Uses RPC_URL from environment variable

[signer]
# Uses SIGNER_PRIVATE_KEY from environment variable
type = "env_keypair"

[fees]
# Disable fees for now (we'll add later)
enabled = false

[validation]
# Allow all programs for now
enabled = false
